# Generated by Django 5.0.7 on 2024-08-03 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('subscribers', models.IntegerField(null=True)),
                ('platform', models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('X', 'X'), ('INSTAGRAM', 'INSTAGRAM'), ('TIKTOK', 'TIKTOK'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('content_id', models.CharField(max_length=255, null=True, verbose_name='Content ID')),
                ('link', models.CharField(max_length=255)),
                ('seized_top', models.BooleanField(null=True, verbose_name='seized top')),
                ('views', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('shares', models.IntegerField(null=True)),
                ('comments', models.IntegerField(null=True)),
                ('published_at', models.DateTimeField(default=datetime.datetime(2024, 8, 3, 14, 11, 6, 319840, tzinfo=datetime.timezone.utc), verbose_name='published at')),
                ('title', models.CharField(max_length=255, null=True)),
                ('reason', models.TextField(null=True)),
                ('through_suggestion', models.BooleanField(null=True, verbose_name='through suggestion')),
                ('status', models.CharField(choices=[('IN PROGRESS', 'IN_PROGRESS'), ('TO DO', 'TO_DO'), ('DONE', 'DONE'), ('REJECTED', 'REJECTED'), ('NOT LABELED', 'NOT_LABELED')], default='NOT LABELED', max_length=20)),
            ],
        ),
    ]
