# Generated by Django 5.0.7 on 2024-08-01 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 10, 2, 20, 923982, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='comments',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='link',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='reason',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='seized_top',
            field=models.BooleanField(default=None, verbose_name='seized top'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='shares',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='subscribers',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='through_suggestion',
            field=models.BooleanField(default=None, verbose_name='through suggestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='views',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
