# Generated by Django 5.0.7 on 2024-08-05 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 10, 16, 34, 893642, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='highlightmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 10, 16, 34, 894521, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
    ]
