# Generated by Django 5.0.7 on 2024-08-01 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contentmodel_added_date_contentmodel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 10, 5, 32, 206722, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
    ]
