# Generated by Django 5.0.7 on 2024-08-05 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contentmodel_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 11, 13, 27, 827452, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 11, 13, 27, 828305, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
    ]
