# Generated by Django 5.0.7 on 2024-08-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contentmodel_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 10, 30, 8, 914767, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='seized_top',
            field=models.BooleanField(null=True, verbose_name='seized top'),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='shares',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='subscribers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='through_suggestion',
            field=models.BooleanField(null=True, verbose_name='through suggestion'),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
