# Generated by Django 5.0.7 on 2024-08-01 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contentmodel_title_alter_contentmodel_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'IN_PROGRESS'), ('TO DO', 'TO_DO'), ('DONE', 'DONE'), ('REJECTED', 'REJECTED'), ('NOT LABELED', 'NOT_LABELED')], default='NOT LABELED', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 13, 48, 36, 362835, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
    ]
