# Generated by Django 5.0.7 on 2024-08-03 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contentmodel_status_alter_contentmodel_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='platform',
            field=models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('X', 'X'), ('INSTAGRAM', 'INSTAGRAM'), ('TIKTOK', 'TIKTOK'), ('OTHER', 'OTHER')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 5, 33, 28, 999505, tzinfo=datetime.timezone.utc), verbose_name='added date'),
        ),
    ]
