services:
  main-app:
    build:
      context: ../..
      dockerfile: .docker/local_postgres/Dockerfile
    container-name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    commands: "sh entrypoint.sh"
    env_file:
      - ../prod.env
    depends_on:
      postgres
    volumes:
      - ..:/app/
